### ISSUE TITLE
Issues with installing OpenCV on JS 

### ISSUE THREAD

**Issue by jonathan-noble** [jonathan-noble/SpotiFace#1]
* OpenCV => 4.0.1 and previous versions
* Operating System / Platform =>  Windows 10 64 Bit
* Compiler => Visual Studio 2017

I am on the process of installing OpenCV JS to rewrite the emotion_detector.py into JS for web app deployment and I've encountered simple errors here and there that can be found by searching via Google.
However, I'm currently on an error that is irresolvable at the moment and is something out of my limit. I'm about to build opencv.js with this:
`python build_js.py build_js --emscripten_dir=C:\Users\schma\Documents\DulChunCinn\opencv-js\emsdk`

And this is the error I get:
```
CMake Error at cmake/OpenCVDetectCXXCompiler.cmake:186 (message):
  OpenCV 4.x requires C++11
Call Stack (most recent call first):
  CMakeLists.txt:156 (include)


-- Configuring incomplete, errors occurred!
See also "C:/Users/schma/Documents/DulChunCinn/opencv-js/opencv/platforms/js/build_js/CMakeFiles/CMakeOutput.log".
See also "C:/Users/schma/Documents/DulChunCinn/opencv-js/opencv/platforms/js/build_js/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "build_js.py", line 227, in <module>
    builder.config()
  File "build_js.py", line 167, in config
    execute(cmd)
  File "build_js.py", line 23, in execute
    raise Fail("Child returned: %s" % retcode)
__main__.Fail: Child returned: 1

```
I will have to opt with Tracking.js as it's currently not compatible with the configuration of Windows 10.

**Comment by jonathan-noble** [comment]
Using the dependency react-webcam instead as it returns a base64 encoded image.
